name: 'Deploy Databricks Assets'

on:
  push:
    branches:
      - main
    paths:
      - 'src/databricks/**'
  workflow_dispatch:

permissions:
  contents: read

env:
    DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
    DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    JOB_NAME: "Medallion-Pipeline-CI-CD"

jobs:
  deploy-databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy Databricks Notebooks
        run: |
          databricks workspace import-dir src/databricks /delijn_project --overwrite

      - name: Find existing job ID
        id: find_job
        run: |
          JOB_ID=$(databricks jobs list --name ${{env.JOB_NAME}} --output JSON | jq -r '.[0].job_id // empty')
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

      - name: Create or Update Databricks Job
        run: |
          if [ -z "${{ env.JOB_ID }}" ]; then
            echo "Creating new job..."
            databricks jobs create --json @src/databricks/medallion_job.json
          else
            echo "Updating existing job ${{ env.JOB_ID }}..."
            RESET_JSON=$(jq --argjson j_id ${{ env.JOB_ID }} '{ "job_id": $j_id, "new_settings": . }' src/databricks/medallion_job.json)
            databricks jobs reset --json "${RESET_JSON}"
          fi