name: 'Deploy Infrastructure'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=./terraform init

      - name: Terraform Plan
        run: terraform -chdir=./terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=./terraform apply -auto-approve tfplan