name: 'Deploy Function App Code'

on:
  push:
    branches:
      - main
    paths:
      - 'src/functions/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-function-app:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: 'Set up Python 3.12'
        uses: actions/setup-python@main
        with:
          python-version: 3.12

      - name: 'Install dependencies and zip artifact'
        run: |
          cd src/functions
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt
          zip -r ../../release.zip .

      - name: Login to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Functions'
        uses: azure/functions-action@v1.5.3
        with:
          app-name: 'func-delijn-ingest'
          package: 'release.zip'